### ISSUE TITLE
All validators page will likely show mostly non-delegated validators, consider displaying VP instead of users delegations 

### ISSUE THREAD

**Issue by cmancrypto** [Orchestra-Labs/Browser-Extension-Wallet#29]

**Comment by dblackstone1** [comment]
as configurable, sure, but most users won't care about voting power.  they'll care about APR, APY, or uptime

**Comment by cmancrypto** [comment]
If the VP is concentrated there's a real risk to the oracle.
As far as I know every wallet and every explorer has VP as the default ordering because of the centralization risk. 
Stakers tend to be long term project aligned because they have a long time period undelegate - so keeping the chain healthy is likely to be caring about money. 

The commission is the next most important and is basically a proxy for APR/APY. 
In cosmos most validators will have the same APR/APY as long as they have the same commission.

**Comment by dblackstone1** [comment]
You can sway people by having the red text "that's bad" warning like here.  That's already enabled for a couple aspects.  But notice in this example they give 3 pieces of information and APY on its own.  That's because users care about that more.  It should be calculated, and it should be an option, but if we don't show users what they want to see in a prominent position, they will go to where they can see it.

Notice, they don't even go to the site for information on the chain.  They should.  Technical people do.  But they don't.  Most don't even read the text on the tasks.  They want to maximize returns.  Expecting people to take the most rational, long term minded action is always a set up for disappointment.  We must align to the users not align them to us.

![Screenshot_20241108_053914](https://github.com/user-attachments/assets/ce8f7fee-7c73-4909-9c9c-972e414921e6)
![Screenshot_20241108_053844](https://github.com/user-attachments/assets/775329e6-4d19-44be-a5e2-9f270ad2a819)
